// ============================================================
// Flowbreeds HQ opening catalogue.
//
// Every product the business was selling at HQ when it moved off the old
// POS, taken from that system's 'Inventory: Location and Category' report
// (location "Flowbreeds Main", printed 08/09/2026). Generated, not typed by
// hand, so the codes match the labels already on the shelves.
//
// Prices are INTEGER ngwee, like everywhere else. `unitOfMeasure` follows how
// the old system counted the line: anything it held in fractions was weighed,
// so it is sold per kg; whole counts are sold each.
//
// A product carries a barcode only where the old system gave it one that
// identifies it uniquely. Five lines have none — four bakery items shared a
// single code between them and one had no code at all — so they import by
// name and a real barcode is scanned onto them from the Products screen.
// ============================================================

export interface CatalogueItem {
  name: string;
  category: string;
  unitPrice: number; // minor units (ngwee)
  unitOfMeasure: string;
  isWeightBased: boolean;
  barcodes: string[];
}

export const HQ_CATALOGUE_SOURCE =
  'Flowbreeds Main (HQ) — previous POS inventory export, 08/09/2026';

export const HQ_CATALOGUE: CatalogueItem[] = [
  { name: 'Agogo brown bread', category: 'Bakery', unitPrice: 2000, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['600963040051'] },
  { name: 'Agogo Butter bread', category: 'Bakery', unitPrice: 2500, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['600980329136'] },
  { name: 'Agogos original white bread', category: 'Bakery', unitPrice: 2500, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['600963040050'] },
  { name: 'Bomfwa super milkbread', category: 'Bakery', unitPrice: 2500, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['734896222856'] },
  { name: 'Bomfwa wholemwal bread', category: 'Bakery', unitPrice: 2500, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['601432670017'] },
  { name: 'Bread rolls', category: 'Bakery', unitPrice: 250, unitOfMeasure: 'each', isWeightBased: false, barcodes: [] },
  { name: 'Buns', category: 'Bakery', unitPrice: 100, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['buns'] },
  { name: 'buns whole tray', category: 'Bakery', unitPrice: 3500, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['tray of buns'] },
  { name: 'Flow breeds white bread', category: 'Bakery', unitPrice: 2200, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['white bread'] },
  { name: 'Flowbreeds brown bread', category: 'Bakery', unitPrice: 2200, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['bread'] },
  { name: 'Fowbreeds buns pan orders K30', category: 'Bakery', unitPrice: 3000, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['whole sale'] },
  { name: 'new order 28', category: 'Bakery', unitPrice: 2800, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['new 1'] },
  { name: 'Ouma Bread', category: 'Bakery', unitPrice: 2400, unitOfMeasure: 'each', isWeightBased: false, barcodes: [] },
  { name: 'Plan Doughnuts', category: 'Bakery', unitPrice: 500, unitOfMeasure: 'each', isWeightBased: false, barcodes: [] },
  { name: 'Ring Doughnuts', category: 'Bakery', unitPrice: 500, unitOfMeasure: 'each', isWeightBased: false, barcodes: [] },
  { name: 'Small vitumbuwa from bakery', category: 'Bakery', unitPrice: 100, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['Small'] },
  { name: 'Whole tray order price Buns', category: 'Bakery', unitPrice: 3000, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['Buns order'] },
  { name: 'Beef Brisket', category: 'Beef', unitPrice: 13000, unitOfMeasure: 'kg', isWeightBased: true, barcodes: ['200004206045'] },
  { name: 'Beef Chuck', category: 'Beef', unitPrice: 12499, unitOfMeasure: 'kg', isWeightBased: true, barcodes: ['200002306937'] },
  { name: 'Beef hooves', category: 'Beef', unitPrice: 7500, unitOfMeasure: 'kg', isWeightBased: true, barcodes: ['200005510175'] },
  { name: 'Beef Liver', category: 'Beef', unitPrice: 10599, unitOfMeasure: 'kg', isWeightBased: true, barcodes: ['200000204929'] },
  { name: 'Beef Mince', category: 'Beef', unitPrice: 13000, unitOfMeasure: 'kg', isWeightBased: true, barcodes: ['200004006045'] },
  { name: 'Beef Offals', category: 'Beef', unitPrice: 7000, unitOfMeasure: 'kg', isWeightBased: true, barcodes: ['200004706405'] },
  { name: 'Beef Shine', category: 'Beef', unitPrice: 12000, unitOfMeasure: 'kg', isWeightBased: true, barcodes: ['200004405580'] },
  { name: 'Beef Short Ribs', category: 'Beef', unitPrice: 12000, unitOfMeasure: 'kg', isWeightBased: true, barcodes: ['200004305580'] },
  { name: 'Beef Shoulder', category: 'Beef', unitPrice: 13000, unitOfMeasure: 'kg', isWeightBased: true, barcodes: ['200005231200'] },
  { name: 'Beef Stew', category: 'Beef', unitPrice: 10000, unitOfMeasure: 'kg', isWeightBased: true, barcodes: ['200002004650'] },
  { name: 'Eco beef sausage', category: 'Beef', unitPrice: 11000, unitOfMeasure: 'kg', isWeightBased: true, barcodes: ['beef sausage'] },
  { name: 'fillet steak', category: 'Beef', unitPrice: 15300, unitOfMeasure: 'kg', isWeightBased: true, barcodes: ['beef'] },
  { name: 'Mince orders 130 per kg', category: 'Beef', unitPrice: 13000, unitOfMeasure: 'kg', isWeightBased: true, barcodes: ['Mince'] },
  { name: 'Ox Tongue', category: 'Beef', unitPrice: 8899, unitOfMeasure: 'kg', isWeightBased: true, barcodes: ['200009008677'] },
  { name: 'Packed beef bones', category: 'Beef', unitPrice: 2500, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['Bones beef'] },
  { name: 'Steak On Bone', category: 'Beef', unitPrice: 14500, unitOfMeasure: 'kg', isWeightBased: true, barcodes: ['200002106789'] },
  { name: 'STEAK ON bONE ORDERS', category: 'Beef', unitPrice: 12500, unitOfMeasure: 'kg', isWeightBased: true, barcodes: ['200007423813'] },
  { name: 'T-Bone Steak', category: 'Beef', unitPrice: 15500, unitOfMeasure: 'kg', isWeightBased: true, barcodes: ['200002207208'] },
  { name: 'Ole Cooking Oil (5lts)', category: 'Cooking Oil', unitPrice: 25500, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['600967425008'] },
  { name: 'Packed Cooking Oil', category: 'Cooking Oil', unitPrice: 200, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['pamoil1'] },
  { name: 'smallest', category: 'Cooking Oil', unitPrice: 100, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['Cooking oil'] },
  { name: 'Zam Gold (500ml)', category: 'Cooking Oil', unitPrice: 3500, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['734800891537'] },
  { name: 'Zam Gold (750ml)', category: 'Cooking Oil', unitPrice: 4500, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['600970616049'] },
  { name: 'Zam Gold(2.5lts)', category: 'Cooking Oil', unitPrice: 14000, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['600970616051'] },
  { name: 'Zamgold (2lts)', category: 'Cooking Oil', unitPrice: 12000, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['600970616050'] },
  { name: 'ZamGold (5Ltrs)', category: 'Cooking Oil', unitPrice: 26500, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['600970616058'] },
  { name: 'Big fresh kapenta', category: 'Fish', unitPrice: 2300, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['200009102320'] },
  { name: 'Flowbreeds Fresh Fish', category: 'Fish', unitPrice: 6599, unitOfMeasure: 'kg', isWeightBased: true, barcodes: ['200001803069'] },
  { name: 'Fresh Fish Large', category: 'Fish', unitPrice: 7599, unitOfMeasure: 'kg', isWeightBased: true, barcodes: ['200001703534'] },
  { name: 'Fresh Fish oders', category: 'Fish', unitPrice: 7000, unitOfMeasure: 'kg', isWeightBased: true, barcodes: ['200007235840'] },
  { name: 'Fresh fish orderd K72 per kg', category: 'Fish', unitPrice: 7200, unitOfMeasure: 'kg', isWeightBased: true, barcodes: ['Fish orders'] },
  { name: 'Fresh Fish Small', category: 'Fish', unitPrice: 5599, unitOfMeasure: 'kg', isWeightBased: true, barcodes: ['200001902604'] },
  { name: 'ITEZHITEZHI NEW', category: 'Fish', unitPrice: 3000, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['Kapenta F'] },
  { name: 'Packed dry Lasa-lasa', category: 'Fish', unitPrice: 500, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['Kapenta'] },
  { name: 'Packed Kapenta dry small', category: 'Fish', unitPrice: 1000, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['Dry kapenta'] },
  { name: 'Packs of fresh Kapenta', category: 'Fish', unitPrice: 2000, unitOfMeasure: 'kg', isWeightBased: true, barcodes: ['200009902001'] },
  { name: 'Small dry fish by 3 reduced', category: 'Fish', unitPrice: 5000, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['Dry fish'] },
  { name: 'Smoked Fish', category: 'Fish', unitPrice: 24000, unitOfMeasure: 'kg', isWeightBased: true, barcodes: ['200005314280'] },
  { name: 'Crembos custard flavour', category: 'Flowbreeds', unitPrice: 700, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['600964492776'] },
  { name: 'eezee noodles beef flavour', category: 'Flowbreeds', unitPrice: 800, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['600981504004'] },
  { name: 'Mosquito Repellent incense', category: 'Flowbreeds', unitPrice: 200, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['692681130029'] },
  { name: 'Smart kleen lemon clean dish', category: 'Flowbreeds', unitPrice: 1200, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['600971510484'] },
  { name: 'Apple medium fruit', category: 'Fruits', unitPrice: 500, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['Apples'] },
  { name: 'Apple small K4', category: 'Fruits', unitPrice: 400, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['Applee'] },
  { name: 'Banana medium', category: 'Fruits', unitPrice: 400, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['Bananas'] },
  { name: 'Natches medium fruit', category: 'Fruits', unitPrice: 500, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['Natches'] },
  { name: 'Dry Impala', category: 'Game Meat', unitPrice: 40000, unitOfMeasure: 'kg', isWeightBased: true, barcodes: ['200003318600'] },
  { name: 'Dry Kudu', category: 'Game Meat', unitPrice: 40000, unitOfMeasure: 'kg', isWeightBased: true, barcodes: ['200003418600'] },
  { name: 'Dry Puku', category: 'Game Meat', unitPrice: 40000, unitOfMeasure: 'kg', isWeightBased: true, barcodes: ['200003618600'] },
  { name: 'Dry Warthog', category: 'Game Meat', unitPrice: 40000, unitOfMeasure: 'kg', isWeightBased: true, barcodes: ['200003518600'] },
  { name: 'Dry Water Back', category: 'Game Meat', unitPrice: 40000, unitOfMeasure: 'kg', isWeightBased: true, barcodes: ['200003818600'] },
  { name: 'Fresh Impala', category: 'Game Meat', unitPrice: 19500, unitOfMeasure: 'kg', isWeightBased: true, barcodes: ['200002409068'] },
  { name: 'Fresh Kudu', category: 'Game Meat', unitPrice: 19500, unitOfMeasure: 'kg', isWeightBased: true, barcodes: ['200002509068'] },
  { name: 'Fresh Puku', category: 'Game Meat', unitPrice: 19500, unitOfMeasure: 'kg', isWeightBased: true, barcodes: ['200002809068'] },
  { name: 'Fresh Sable', category: 'Game Meat', unitPrice: 19500, unitOfMeasure: 'kg', isWeightBased: true, barcodes: ['200002909068'] },
  { name: 'Fresh Warthog', category: 'Game Meat', unitPrice: 20500, unitOfMeasure: 'kg', isWeightBased: true, barcodes: ['200002709068'] },
  { name: 'Fresh Water Back', category: 'Game Meat', unitPrice: 19500, unitOfMeasure: 'kg', isWeightBased: true, barcodes: ['200003009068'] },
  { name: 'Goat Offals', category: 'Game Meat', unitPrice: 5300, unitOfMeasure: 'kg', isWeightBased: true, barcodes: ['200004805194'] },
  { name: 'Goat Liver', category: 'Goat / Mutton', unitPrice: 6500, unitOfMeasure: 'kg', isWeightBased: true, barcodes: ['200005006175'] },
  { name: 'Goat Stew', category: 'Goat / Mutton', unitPrice: 13000, unitOfMeasure: 'kg', isWeightBased: true, barcodes: ['200000506045'] },
  { name: 'Lamb Lion Chops', category: 'Goat / Mutton', unitPrice: 15099, unitOfMeasure: 'kg', isWeightBased: true, barcodes: ['200000309114'] },
  { name: 'Lamb Offals', category: 'Goat / Mutton', unitPrice: 5500, unitOfMeasure: 'kg', isWeightBased: true, barcodes: ['200004910423'] },
  { name: 'Lamb Stew', category: 'Goat / Mutton', unitPrice: 15000, unitOfMeasure: 'kg', isWeightBased: true, barcodes: ['200000406975'] },
  { name: 'Agogo premium white milk bread', category: 'Groceries', unitPrice: 2500, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['600980329133'] },
  { name: 'AK Salt 500G', category: 'Groceries', unitPrice: 600, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['811700357813'] },
  { name: 'ALOHA S. RAIN Washing', category: 'Groceries', unitPrice: 25800, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['600970982207'] },
  { name: 'ALOHA S. RAIN Washing', category: 'Groceries', unitPrice: 12500, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['600970982209'] },
  { name: 'ALOHA S.RAIN Washing Powder', category: 'Groceries', unitPrice: 4000, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['600970982162'] },
  { name: 'Aloha savana rain 150g', category: 'Groceries', unitPrice: 1500, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['600970982214'] },
  { name: 'Anjoy cola flavour', category: 'Groceries', unitPrice: 100, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['600964492167'] },
  { name: 'Anjoy orange flavour', category: 'Groceries', unitPrice: 100, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['600964492164'] },
  { name: 'Anjoy pineaple flavour', category: 'Groceries', unitPrice: 100, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['600964492165'] },
  { name: 'Anjoy Rasberry (5g)', category: 'Groceries', unitPrice: 100, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['600964492166'] },
  { name: 'Aspirin/caffenine tablets', category: 'Groceries', unitPrice: 100, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['Cafemol'] },
  { name: 'Assorted Spices', category: 'Groceries', unitPrice: 1000, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['assortedspices'] },
  { name: 'Banja washing powder 250g', category: 'Groceries', unitPrice: 2300, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['600970982937'] },
  { name: 'BARAKA RICE', category: 'Groceries', unitPrice: 3000, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['896901105104'] },
  { name: 'Bella Spaghetti', category: 'Groceries', unitPrice: 2000, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['600980863031'] },
  { name: 'Biggy Bottlo chibwantu (750ml)', category: 'Groceries', unitPrice: 1200, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['611355387281'] },
  { name: 'Bigtree BINTO Noodels Spicy', category: 'Groceries', unitPrice: 800, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['600971310199'] },
  { name: 'Binto BBQ Spice', category: 'Groceries', unitPrice: 1200, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['600971310758'] },
  { name: 'Binto Beef Spice', category: 'Groceries', unitPrice: 1200, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['600971310754'] },
  { name: 'Binto chicken powdered', category: 'Groceries', unitPrice: 200, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['600971510153'] },
  { name: 'Binto noodles beef flavour', category: 'Groceries', unitPrice: 800, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['600971310200'] },
  { name: 'Binto noodles spicy chicken', category: 'Groceries', unitPrice: 800, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['600971310396'] },
  { name: 'Binto portuguese chicken spice', category: 'Groceries', unitPrice: 1200, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['600971310752'] },
  { name: 'Binto Rice Spice', category: 'Groceries', unitPrice: 1200, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['600971310760'] },
  { name: 'Binto spice T bone', category: 'Groceries', unitPrice: 1000, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['600971310753'] },
  { name: 'Blank Washing powder 500g', category: 'Groceries', unitPrice: 1500, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['796554368368'] },
  { name: 'Blue Band (100g)', category: 'Groceries', unitPrice: 1500, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['61614000'] },
  { name: 'Blue Band (250g)', category: 'Groceries', unitPrice: 3500, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['616400467623'] },
  { name: 'Boom bubble pls 150g', category: 'Groceries', unitPrice: 1600, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['600964492346'] },
  { name: 'Boom bubble plus 12g', category: 'Groceries', unitPrice: 100, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['600970982662'] },
  { name: 'BOOM DISH LIQUID 750mls', category: 'Groceries', unitPrice: 4500, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['600964492560'] },
  { name: 'BOOM dishwashing liquid 400mls', category: 'Groceries', unitPrice: 3000, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['600964492557'] },
  { name: 'BOOM Washing PASTE 400G', category: 'Groceries', unitPrice: 2500, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['600964492016'] },
  { name: 'Brown Sugar 330g', category: 'Groceries', unitPrice: 1200, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['600967089005'] },
  { name: 'Brown sugar 70g', category: 'Groceries', unitPrice: 300, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['600967089011'] },
  { name: 'Bullet dishwashing liquid 750mls', category: 'Groceries', unitPrice: 2500, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['600970982681'] },
  { name: 'Bullet washing powder 150g', category: 'Groceries', unitPrice: 1200, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['600964499703'] },
  { name: 'Cafemol', category: 'Groceries', unitPrice: 100, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['600964701026'] },
  { name: 'Carino spaggetti', category: 'Groceries', unitPrice: 1600, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['622400834523'] },
  { name: 'Carino Spaghetti (400g)', category: 'Groceries', unitPrice: 2000, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['622400834452'] },
  { name: 'Chapa Baking Powder (100mg)', category: 'Groceries', unitPrice: 1500, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['616110166171'] },
  { name: 'Chicco cake Vanilla', category: 'Groceries', unitPrice: 300, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['629110308046'] },
  { name: 'Chuma Chips Double Cheese', category: 'Groceries', unitPrice: 100, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['629110308838'] },
  { name: 'Chuma Chips sweet chilli (100g)', category: 'Groceries', unitPrice: 100, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['629110308392'] },
  { name: 'Cockroaches Killer 8g', category: 'Groceries', unitPrice: 300, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['697451243050'] },
  { name: 'Colgate charcoal', category: 'Groceries', unitPrice: 3300, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['871895135088'] },
  { name: 'Colgate herbal healthy gums', category: 'Groceries', unitPrice: 2500, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['692035481782'] },
  { name: 'Colgate max cavity protection', category: 'Groceries', unitPrice: 2500, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['885000632442'] },
  { name: 'Continental mealie meal', category: 'Groceries', unitPrice: 29000, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['600198311044'] },
  { name: 'Continental mealiemeal breakfast', category: 'Groceries', unitPrice: 16000, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['600198311045'] },
  { name: 'Continental mealimeal breakfast', category: 'Groceries', unitPrice: 14000, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['600198311223'] },
  { name: 'Continental roller meal 25kgs', category: 'Groceries', unitPrice: 22000, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['600990048879'] },
  { name: 'Cream It (10g)', category: 'Groceries', unitPrice: 200, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['600970982332'] },
  { name: 'Creambell Milk (500ml)', category: 'Groceries', unitPrice: 1600, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['600980367204'] },
  { name: 'Creambell milk poch 225ml', category: 'Groceries', unitPrice: 900, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['600988870147'] },
  { name: 'Creambell Plus poch milk 500ml', category: 'Groceries', unitPrice: 1500, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['600988870134'] },
  { name: 'D\'lite baby cereal wheat', category: 'Groceries', unitPrice: 800, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['600964492450'] },
  { name: 'D\'lite cooking oil 750 mls', category: 'Groceries', unitPrice: 4200, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['600156500902'] },
  { name: 'Dairy Gold Milk (250ml)', category: 'Groceries', unitPrice: 900, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['600971132226'] },
  { name: 'Dairy gold milk 500mls', category: 'Groceries', unitPrice: 1500, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['600970982928'] },
  { name: 'Dairy old 500ml tetra', category: 'Groceries', unitPrice: 1600, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['600971132246'] },
  { name: 'Dettol original', category: 'Groceries', unitPrice: 2000, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['600110622499'] },
  { name: 'Dettol skincare 175g', category: 'Groceries', unitPrice: 2000, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['600110622604'] },
  { name: 'Dlite Banana (50g)', category: 'Groceries', unitPrice: 500, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['600964492452'] },
  { name: 'Dorco razor blades whole pack', category: 'Groceries', unitPrice: 700, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['880103820004'] },
  { name: 'eeZee Noodles Chicken (120g)', category: 'Groceries', unitPrice: 800, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['74585393307'] },
  { name: 'Eggs Big Size', category: 'Groceries', unitPrice: 400, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['eggs2'] },
  { name: 'Eggs Nornal Size', category: 'Groceries', unitPrice: 300, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['eggs1'] },
  { name: 'Embe mango drink 399ml', category: 'Groceries', unitPrice: 800, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['620301106080'] },
  { name: 'Embe mango drink 500ml', category: 'Groceries', unitPrice: 1500, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['620301106132'] },
  { name: 'Finta (500ml)', category: 'Groceries', unitPrice: 1500, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['600960140000'] },
  { name: 'Grown ups d\'lite', category: 'Groceries', unitPrice: 2500, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['600953701503'] },
  { name: 'Handy Andy', category: 'Groceries', unitPrice: 4200, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['600108739173'] },
  { name: 'Household Sugar (2KG)', category: 'Groceries', unitPrice: 7000, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['710535375237'] },
  { name: 'Iodated Fine salt 500g', category: 'Groceries', unitPrice: 600, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['728990417188'] },
  { name: 'JK Iodated salt 1kg', category: 'Groceries', unitPrice: 1200, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['600980943002'] },
  { name: 'JK loose black tea 7g', category: 'Groceries', unitPrice: 100, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['733189873552'] },
  { name: 'JK Salt 500g', category: 'Groceries', unitPrice: 800, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['600980943001'] },
  { name: 'JK Salt K6', category: 'Groceries', unitPrice: 600, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['Salt'] },
  { name: 'Life buoy lemon fresh', category: 'Groceries', unitPrice: 2000, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['600108735865'] },
  { name: 'Life buoy total', category: 'Groceries', unitPrice: 2000, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['600108735861'] },
  { name: 'Lifebuoy Herbal', category: 'Groceries', unitPrice: 2000, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['600108735863'] },
  { name: 'Luck Star Hot (155g)', category: 'Groceries', unitPrice: 2500, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['600111500061'] },
  { name: 'Luck Star Tomato (155g)', category: 'Groceries', unitPrice: 2500, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['600111500057'] },
  { name: 'LUCKY STAR HOT CHILI', category: 'Groceries', unitPrice: 3600, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['501082113100'] },
  { name: 'Lucky star pilchards tomato', category: 'Groceries', unitPrice: 3600, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['501082112100'] },
  { name: 'Mabisi 500ml', category: 'Groceries', unitPrice: 1600, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['600967221007'] },
  { name: 'Mama\'s cooking oil 750 mls', category: 'Groceries', unitPrice: 4200, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['869010199288'] },
  { name: 'Mamas pride spagetti', category: 'Groceries', unitPrice: 1000, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['600966809215'] },
  { name: 'Mansa sugar 1kg', category: 'Groceries', unitPrice: 3600, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['710535375404'] },
  { name: 'Mansa Sugar 1kg', category: 'Groceries', unitPrice: 3600, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['710535375244'] },
  { name: 'Mariana White Rice 500g', category: 'Groceries', unitPrice: 2500, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['950400018107'] },
  { name: 'Matches', category: 'Groceries', unitPrice: 100, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['717400064310'] },
  { name: 'Medi HerbAYURVEDI HERBAL', category: 'Groceries', unitPrice: 1500, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['600970982230'] },
  { name: 'medium eggs normal', category: 'Groceries', unitPrice: 350, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['medium eggs'] },
  { name: 'Milano macroni', category: 'Groceries', unitPrice: 2000, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['600965278805'] },
  { name: 'MILK SHAKE STRAWBERRY', category: 'Groceries', unitPrice: 1000, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['792649791172'] },
  { name: 'Milkit milkshake chocolate 250ml', category: 'Groceries', unitPrice: 1000, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['600964499709'] },
  { name: 'Milkit vanilla flavour', category: 'Groceries', unitPrice: 1000, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['600964499711'] },
  { name: 'Mister CHILI Peri peri', category: 'Groceries', unitPrice: 2000, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['600964492816'] },
  { name: 'Mix it Cola flavour 5g', category: 'Groceries', unitPrice: 100, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['764460990270'] },
  { name: 'Mojo ginger 330ml', category: 'Groceries', unitPrice: 600, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['600964499618'] },
  { name: 'Mortein mukti insect killer lemon', category: 'Groceries', unitPrice: 5500, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['600110622554'] },
  { name: 'Mountain Dew 2ltrs', category: 'Groceries', unitPrice: 2800, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['600980322750'] },
  { name: 'Mygold tea 10g', category: 'Groceries', unitPrice: 100, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['462687230010'] },
  { name: 'Nakonde rice 500g', category: 'Groceries', unitPrice: 2300, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['200008602300'] },
  { name: 'ndiyo mix beef spice 100g', category: 'Groceries', unitPrice: 200, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['600953701462'] },
  { name: 'ndiyo mix chicken spice', category: 'Groceries', unitPrice: 200, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['600953701460'] },
  { name: 'Nyama ya ngombe soya pieces', category: 'Groceries', unitPrice: 800, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['600988091621'] },
  { name: 'Onga beef flavour 8g', category: 'Groceries', unitPrice: 200, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['600815501650'] },
  { name: 'P.S. Cadbury 19g', category: 'Groceries', unitPrice: 800, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['762221084187'] },
  { name: 'Packaged Rice (1.5kg)', category: 'Groceries', unitPrice: 5000, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['pamrice1'] },
  { name: 'Packed Beans', category: 'Groceries', unitPrice: 1000, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['beansp'] },
  { name: 'Packed beans K15', category: 'Groceries', unitPrice: 1500, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['Beans'] },
  { name: 'Packed Cassava Meal (10)', category: 'Groceries', unitPrice: 1000, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['pamcassava10'] },
  { name: 'Packed Cassava Meal (5)', category: 'Groceries', unitPrice: 500, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['pamcassava5'] },
  { name: 'Packed Maize Meal (10)', category: 'Groceries', unitPrice: 1000, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['pammeal10'] },
  { name: 'Packed Maize Meal(5)', category: 'Groceries', unitPrice: 500, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['meallie5'] },
  { name: 'Packed ponded groundnuts', category: 'Groceries', unitPrice: 1000, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['G.nuts'] },
  { name: 'Packed Rice Small', category: 'Groceries', unitPrice: 1000, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['packers'] },
  { name: 'Packed Soda', category: 'Groceries', unitPrice: 500, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['pamsoda1'] },
  { name: 'packed whole groundnuts', category: 'Groceries', unitPrice: 1000, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['Groundnuts'] },
  { name: 'Panado paracetamol', category: 'Groceries', unitPrice: 100, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['Panado'] },
  { name: 'Paracetamol 1*10', category: 'Groceries', unitPrice: 500, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['890604711020'] },
  { name: 'Peanut butter Everyday', category: 'Groceries', unitPrice: 3500, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['705632553961'] },
  { name: 'Pembe breakfast 25kg', category: 'Groceries', unitPrice: 31000, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['600969700279'] },
  { name: 'Pembe Roller meal', category: 'Groceries', unitPrice: 25000, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['600969700282'] },
  { name: 'Protex herbal 175g', category: 'Groceries', unitPrice: 2000, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['871895169790'] },
  { name: 'Quivck brew black tea', category: 'Groceries', unitPrice: 2500, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['600484200151'] },
  { name: 'Raja curry mild and spicy', category: 'Groceries', unitPrice: 2500, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['600103820315'] },
  { name: 'RAZOR ONE STRIP', category: 'Groceries', unitPrice: 150, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['880103820036'] },
  { name: 'Rhodes Baked Bean (410g)', category: 'Groceries', unitPrice: 3000, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['600504400037'] },
  { name: 'Rivonia mixed fruit jam', category: 'Groceries', unitPrice: 3500, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['600960844027'] },
  { name: 'Rivonis starwberry jam', category: 'Groceries', unitPrice: 3501, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['600960844026'] },
  { name: 'ROYCO Mchuzi mix 8g beef', category: 'Groceries', unitPrice: 200, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['616111517283'] },
  { name: 'RUSH PINEAPPLE', category: 'Groceries', unitPrice: 1000, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['700083060853'] },
  { name: 'Salted crackers (100)', category: 'Groceries', unitPrice: 1300, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['600982983072'] },
  { name: 'Sebas Soya Pieces Chicken', category: 'Groceries', unitPrice: 1000, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['600988075573'] },
  { name: 'Shenke botanical mosquito coil', category: 'Groceries', unitPrice: 200, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['695393718602'] },
  { name: 'Smart kleen washing powder', category: 'Groceries', unitPrice: 1500, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['600971310742'] },
  { name: 'SOBI exercise book small 40', category: 'Groceries', unitPrice: 200, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['600965278215'] },
  { name: 'Soya Chunks', category: 'Groceries', unitPrice: 500, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['soyachunks1'] },
  { name: 'Soya gold soya pieces', category: 'Groceries', unitPrice: 800, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['799439793132'] },
  { name: 'Super Maheu chocolate and Milk', category: 'Groceries', unitPrice: 2500, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['600964492118'] },
  { name: 'Super Maheu Milk and Cream', category: 'Groceries', unitPrice: 2500, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['600964492114'] },
  { name: 'Super maheu strawbwerry yogurt', category: 'Groceries', unitPrice: 2500, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['600980259115'] },
  { name: 'Sweet Leaf Ginger Tea (18g)', category: 'Groceries', unitPrice: 500, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['600964499721'] },
  { name: 'Sweet leaf tea 18g', category: 'Groceries', unitPrice: 400, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['600964499720'] },
  { name: 'Tangy Mayonnaise (750g)', category: 'Groceries', unitPrice: 7200, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['600952230126'] },
  { name: 'Tea bags JK', category: 'Groceries', unitPrice: 2500, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['632286027916'] },
  { name: 'Teabags', category: 'Groceries', unitPrice: 50, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['JK teabags one'] },
  { name: 'Tiger safety Matches', category: 'Groceries', unitPrice: 100, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['600990003202'] },
  { name: 'Tinga tinga cheese n onion', category: 'Groceries', unitPrice: 100, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['600988060774'] },
  { name: 'tinga tinga fruit chutney', category: 'Groceries', unitPrice: 100, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['600988060775'] },
  { name: 'Tingling ginger beer (non', category: 'Groceries', unitPrice: 1200, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['600965278568'] },
  { name: 'Tips (62.5g)', category: 'Groceries', unitPrice: 1300, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['600541800278'] },
  { name: 'Tomato ketchup Rivonia', category: 'Groceries', unitPrice: 2500, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['600960844009'] },
  { name: 'Ultra breadspread 500g', category: 'Groceries', unitPrice: 3000, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['600111400276'] },
  { name: 'v', category: 'Groceries', unitPrice: 100, unitOfMeasure: 'each', isWeightBased: false, barcodes: [] },
  { name: 'Vatra 330 mls', category: 'Groceries', unitPrice: 400, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['600971132823'] },
  { name: 'Well splash mineral water', category: 'Groceries', unitPrice: 300, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['635909998426'] },
  { name: 'Whitespon Brown Sugar (195g)', category: 'Groceries', unitPrice: 800, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['600967089002'] },
  { name: 'Whitespon Sugar (1kg)', category: 'Groceries', unitPrice: 3600, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['600967089202'] },
  { name: 'Whitespon Sugar (2kg)', category: 'Groceries', unitPrice: 7000, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['600967089203'] },
  { name: 'yamene naks BBQ beef 100g', category: 'Groceries', unitPrice: 50, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['600990007671'] },
  { name: 'Yebo medicated soap', category: 'Groceries', unitPrice: 1500, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['600970982064'] },
  { name: 'yellow pencil', category: 'Groceries', unitPrice: 100, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['Pencils'] },
  { name: 'Yess Giner Beer 350ml', category: 'Groceries', unitPrice: 700, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['606110287753'] },
  { name: 'Zam Spread Peanut Butter', category: 'Groceries', unitPrice: 3000, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['745853514341'] },
  { name: 'Zamgold 500mls', category: 'Groceries', unitPrice: 3500, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['600970616093'] },
  { name: 'Zamilk Vanilla Mabisi', category: 'Groceries', unitPrice: 850, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['600967221759'] },
  { name: 'Zamlite matches', category: 'Groceries', unitPrice: 100, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['762083241885'] },
  { name: 'Zammilk Strawberry Mabisi', category: 'Groceries', unitPrice: 850, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['600967221795'] },
  { name: 'Zammilk Sweetened 250ml', category: 'Groceries', unitPrice: 850, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['600967221760'] },
  { name: 'Zamspread Peanut Butter (310)', category: 'Groceries', unitPrice: 2800, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['074585351434'] },
  { name: 'zamspread peanut butter 20g', category: 'Groceries', unitPrice: 200, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['658325913422'] },
  { name: 'Ama sipsip maheu chocolate', category: 'Juices', unitPrice: 800, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['600971132577'] },
  { name: 'Fruitop Grape (1.5lts)', category: 'Juices', unitPrice: 4000, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['600970982832'] },
  { name: 'Fruitop Orange (1.5lts)', category: 'Juices', unitPrice: 4000, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['600970982466'] },
  { name: 'Fruitop Pineapple (1.5lts)', category: 'Juices', unitPrice: 4000, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['600970982465'] },
  { name: 'Go fresh pineapple squash', category: 'Juices', unitPrice: 4000, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['600964492524'] },
  { name: 'Groovy sip green apple', category: 'Juices', unitPrice: 100, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['710497449908'] },
  { name: 'Groovy sip tutti fruity', category: 'Juices', unitPrice: 100, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['710497449939'] },
  { name: 'Juice-it Milky pineapple', category: 'Juices', unitPrice: 1000, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['600964499332'] },
  { name: 'Just Granadilla', category: 'Juices', unitPrice: 5000, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['600965278257'] },
  { name: 'Just Pineapple (2.5lts)', category: 'Juices', unitPrice: 5000, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['600965278256'] },
  { name: 'Mazoe Blackcurrant 2litres', category: 'Juices', unitPrice: 4500, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['544900013121'] },
  { name: 'MAZOE CREAM SODA', category: 'Juices', unitPrice: 6500, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['544900024386'] },
  { name: 'Mazoe Raspberry (2lts)', category: 'Juices', unitPrice: 5500, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['544900024420'] },
  { name: 'MILK SHAKE CHOCOLATE', category: 'Juices', unitPrice: 1000, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['792649791189'] },
  { name: 'Milkit Banana flavour', category: 'Juices', unitPrice: 1000, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['600964499708'] },
  { name: 'RUSH MANGO', category: 'Juices', unitPrice: 1000, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['700083060860'] },
  { name: 'RUSH MIXED FRUIT', category: 'Juices', unitPrice: 1000, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['700083060884'] },
  { name: 'RUSH ORANGE', category: 'Juices', unitPrice: 1000, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['700083060846'] },
  { name: 'Sobo Orange (2lts)', category: 'Juices', unitPrice: 8500, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['600968333003'] },
  { name: 'Sobo pine apple flavour', category: 'Juices', unitPrice: 8500, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['600968333098'] },
  { name: 'Super maheu', category: 'Juices', unitPrice: 2500, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['600964492113'] },
  { name: 'Chili bites one each', category: 'Polony Products', unitPrice: 800, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['200090200006'] },
  { name: 'Cooked salami', category: 'Polony Products', unitPrice: 18000, unitOfMeasure: 'kg', isWeightBased: true, barcodes: ['200000003167'] },
  { name: 'French Polony', category: 'Polony Products', unitPrice: 12000, unitOfMeasure: 'kg', isWeightBased: true, barcodes: ['200005128800'] },
  { name: 'Pork Chops Orders', category: 'Pork', unitPrice: 13000, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['200007340885'] },
  { name: 'Pork Leg Chop', category: 'Pork', unitPrice: 14699, unitOfMeasure: 'kg', isWeightBased: true, barcodes: ['200000906789'] },
  { name: 'Pork Lion Chops', category: 'Pork', unitPrice: 14500, unitOfMeasure: 'kg', isWeightBased: true, barcodes: ['200000606743'] },
  { name: 'Pork Rashers', category: 'Pork', unitPrice: 9699, unitOfMeasure: 'kg', isWeightBased: true, barcodes: ['200001204510'] },
  { name: 'Pork Shoulder Chops', category: 'Pork', unitPrice: 13500, unitOfMeasure: 'kg', isWeightBased: true, barcodes: ['200000806324'] },
  { name: 'Pork Stew', category: 'Pork', unitPrice: 12000, unitOfMeasure: 'kg', isWeightBased: true, barcodes: ['200001005580'] },
  { name: 'Pork Trotters', category: 'Pork', unitPrice: 6599, unitOfMeasure: 'kg', isWeightBased: true, barcodes: ['200001102464'] },
  { name: 'Chicken giblets', category: 'Poultry', unitPrice: 1000, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['sets'] },
  { name: 'Chicken Portions', category: 'Poultry', unitPrice: 8699, unitOfMeasure: 'kg', isWeightBased: true, barcodes: ['200001504045'] },
  { name: 'Half Chicken', category: 'Poultry', unitPrice: 8599, unitOfMeasure: 'kg', isWeightBased: true, barcodes: ['200001603999'] },
  { name: 'Turkey Meat', category: 'Poultry', unitPrice: 13000, unitOfMeasure: 'kg', isWeightBased: true, barcodes: ['Turkey'] },
  { name: 'Whole Chicken', category: 'Poultry', unitPrice: 8990, unitOfMeasure: 'kg', isWeightBased: true, barcodes: ['200005613785'] },
  { name: 'Whole Chicken orders', category: 'Poultry', unitPrice: 13000, unitOfMeasure: 'kg', isWeightBased: true, barcodes: ['200007712675'] },
  { name: 'beef sauasge 130', category: 'Sausage', unitPrice: 13000, unitOfMeasure: 'kg', isWeightBased: true, barcodes: ['Beef sausage'] },
  { name: 'Beef Sausage normal', category: 'Sausage', unitPrice: 13500, unitOfMeasure: 'kg', isWeightBased: true, barcodes: ['200004109653'] },
  { name: 'Beef Sausage orders', category: 'Sausage', unitPrice: 13000, unitOfMeasure: 'kg', isWeightBased: true, barcodes: ['200007640170'] },
  { name: 'Hungarian k13', category: 'Sausage', unitPrice: 1300, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['Sausage'] },
  { name: 'Hungarian Sausage', category: 'Sausage', unitPrice: 11000, unitOfMeasure: 'kg', isWeightBased: true, barcodes: ['200000105050'] },
  { name: '0n the go vanilla', category: 'Snacks', unitPrice: 250, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['600964499646'] },
  { name: 'Amazon bubblegum roll', category: 'Snacks', unitPrice: 100, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['600953701728'] },
  { name: 'amazon bubblegum rolls tutti', category: 'Snacks', unitPrice: 100, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['600953701729'] },
  { name: 'Amazon fruity chewy bar', category: 'Snacks', unitPrice: 100, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['600971132304'] },
  { name: 'Assorted Wrap Sweets', category: 'Snacks', unitPrice: 50, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['assorted111'] },
  { name: 'BIG MUNCH 25g', category: 'Snacks', unitPrice: 300, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['600953702143'] },
  { name: 'Big Munch cheese', category: 'Snacks', unitPrice: 300, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['600953702142'] },
  { name: 'Big Munch Cheese (75g)', category: 'Snacks', unitPrice: 1300, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['600988060763'] },
  { name: 'Bobo biscuit chocolate', category: 'Snacks', unitPrice: 250, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['629110308511'] },
  { name: 'Bobo biscuit milk flavour', category: 'Snacks', unitPrice: 250, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['629110308510'] },
  { name: 'Bono chocolate sandwich cookie', category: 'Snacks', unitPrice: 500, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['600971510072'] },
  { name: 'Bubble gum rolls spearmint', category: 'Snacks', unitPrice: 100, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['600953701727'] },
  { name: 'Bubble Gum Rolls Tutti', category: 'Snacks', unitPrice: 100, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['600957017295'] },
  { name: 'bubble king ball gum', category: 'Snacks', unitPrice: 50, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['600971132397'] },
  { name: 'Cadbury dairy milk top deck', category: 'Snacks', unitPrice: 3000, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['600106560109'] },
  { name: 'Cadbury milk chocolate 37g', category: 'Snacks', unitPrice: 2200, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['600106560130'] },
  { name: 'cadbury Top deck', category: 'Snacks', unitPrice: 2200, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['600106560131'] },
  { name: 'Cardbury dairy milk chocolate', category: 'Snacks', unitPrice: 3000, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['600106560106'] },
  { name: 'Chicco Chocolate (50g)', category: 'Snacks', unitPrice: 300, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['629110308006'] },
  { name: 'Chicco Coconut (50g)', category: 'Snacks', unitPrice: 300, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['629110308008'] },
  { name: 'chicco malt and milk', category: 'Snacks', unitPrice: 300, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['629110308007'] },
  { name: 'Choco dipps', category: 'Snacks', unitPrice: 100, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['600953701684'] },
  { name: 'Choco duo\'s truffeles', category: 'Snacks', unitPrice: 200, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['890610440234'] },
  { name: 'Choco Loco Chocolate paste', category: 'Snacks', unitPrice: 100, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['600971510144'] },
  { name: 'Chuma Chips Fruit Chutney', category: 'Snacks', unitPrice: 100, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['629110308839'] },
  { name: 'Chuma Chips Hot Buffalo', category: 'Snacks', unitPrice: 100, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['629110308390'] },
  { name: 'Chuma Chips Spicy Tomato', category: 'Snacks', unitPrice: 100, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['629110308391'] },
  { name: 'Classy cream vanilla biscuit', category: 'Snacks', unitPrice: 1500, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['890428620018'] },
  { name: 'Classy creme pineapple', category: 'Snacks', unitPrice: 1500, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['890428620015'] },
  { name: 'Classy creme strawberry', category: 'Snacks', unitPrice: 1500, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['890428620016'] },
  { name: 'Cocomo', category: 'Snacks', unitPrice: 500, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['896400107102'] },
  { name: 'Coconut bite', category: 'Snacks', unitPrice: 300, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['600963040023'] },
  { name: 'Colleto creamz', category: 'Snacks', unitPrice: 200, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['890610440190'] },
  { name: 'Crembos cream biscuits', category: 'Snacks', unitPrice: 700, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['600964492773'] },
  { name: 'Crembos cream biscuits small', category: 'Snacks', unitPrice: 100, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['600971310988'] },
  { name: 'CREMBOS STRAWBERRY', category: 'Snacks', unitPrice: 700, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['600964492775'] },
  { name: 'Crembos vanilla flavour', category: 'Snacks', unitPrice: 700, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['600964492774'] },
  { name: 'DEEZ NUTZ', category: 'Snacks', unitPrice: 1000, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['600965278536'] },
  { name: 'Fizz Wizz Apple', category: 'Snacks', unitPrice: 100, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['600953701973'] },
  { name: 'Fizz Wizz Orange', category: 'Snacks', unitPrice: 100, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['600953701968'] },
  { name: 'Funkyz maize snacks', category: 'Snacks', unitPrice: 300, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['600953702141'] },
  { name: 'Ginger cookies joe', category: 'Snacks', unitPrice: 800, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['600971310202'] },
  { name: 'Go-Goes Original', category: 'Snacks', unitPrice: 200, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['600988033074'] },
  { name: 'Joe cookie lemon creams', category: 'Snacks', unitPrice: 800, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['600971132205'] },
  { name: 'Joe cookie milk creams', category: 'Snacks', unitPrice: 800, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['600971132206'] },
  { name: 'Joe Cookie Shortcake', category: 'Snacks', unitPrice: 800, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['600970982775'] },
  { name: 'Joe Cookie Vanilla', category: 'Snacks', unitPrice: 800, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['600971132207'] },
  { name: 'Jolly juice pineapple', category: 'Snacks', unitPrice: 100, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['600969515385'] },
  { name: 'jolly juice raspberry', category: 'Snacks', unitPrice: 100, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['600969515383'] },
  { name: 'Jolly jus Cola', category: 'Snacks', unitPrice: 100, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['600969515381'] },
  { name: 'Jolly jus orange', category: 'Snacks', unitPrice: 100, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['600969515379'] },
  { name: 'Kitkat 20g', category: 'Snacks', unitPrice: 1000, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['600918800274'] },
  { name: 'Lala loops tomatoe flavour', category: 'Snacks', unitPrice: 150, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['600953701851'] },
  { name: 'Lala loops Xxtra', category: 'Snacks', unitPrice: 150, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['600953701850'] },
  { name: 'Lolipop (Big)', category: 'Snacks', unitPrice: 100, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['lolibig1'] },
  { name: 'Lolipop (Small)', category: 'Snacks', unitPrice: 50, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['lolismall1'] },
  { name: 'Milkymoo', category: 'Snacks', unitPrice: 300, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['600953701344'] },
  { name: 'Mix it Orange Flavour', category: 'Snacks', unitPrice: 100, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['764460990256'] },
  { name: 'Mix it P9neapple Flavour', category: 'Snacks', unitPrice: 100, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['764460990263'] },
  { name: 'Mix It Raspberry Flavour', category: 'Snacks', unitPrice: 100, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['764460990287'] },
  { name: 'MIXED CREAM TARTINE DUO', category: 'Snacks', unitPrice: 200, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['618110074025'] },
  { name: 'Mojo Orange 300ml', category: 'Snacks', unitPrice: 600, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['600964499580'] },
  { name: 'Mubabe cheesy onion', category: 'Snacks', unitPrice: 150, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['600988060770'] },
  { name: 'Mubabe nice n spicy', category: 'Snacks', unitPrice: 150, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['600988060773'] },
  { name: 'Mubabe peri peri chicken', category: 'Snacks', unitPrice: 150, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['600988060771'] },
  { name: 'Mubabe Tomato chutney', category: 'Snacks', unitPrice: 150, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['600988060719'] },
  { name: 'Mukaka biscuits', category: 'Snacks', unitPrice: 300, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['600963040081'] },
  { name: 'Musa on the run', category: 'Snacks', unitPrice: 250, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['600987970361'] },
  { name: 'On The Go Chocolate', category: 'Snacks', unitPrice: 250, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['600964499644'] },
  { name: 'Petit beurre biscuit 18g', category: 'Snacks', unitPrice: 100, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['600970982840'] },
  { name: 'PS CARAMEL 48g', category: 'Snacks', unitPrice: 2200, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['600106503408'] },
  { name: 'Ringo puffs chicken flavour', category: 'Snacks', unitPrice: 200, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['781718336666'] },
  { name: 'Ringo snacks', category: 'Snacks', unitPrice: 100, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['781718336529'] },
  { name: 'Salted Crakers (60g)', category: 'Snacks', unitPrice: 700, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['600982983008'] },
  { name: 'SMILYZ Chips', category: 'Snacks', unitPrice: 100, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['600980392864'] },
  { name: 'smilyz chips nice and spicy', category: 'Snacks', unitPrice: 100, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['600980392865'] },
  { name: 'spinners banana strawberry', category: 'Snacks', unitPrice: 200, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['600964492683'] },
  { name: 'sweets K1', category: 'Snacks', unitPrice: 100, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['Sweets'] },
  { name: 'Toffe bar vanilla', category: 'Snacks', unitPrice: 100, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['600970982330'] },
  { name: 'Toffee bar chocolate', category: 'Snacks', unitPrice: 100, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['600970982331'] },
  { name: 'Yamene Naks (100g)', category: 'Snacks', unitPrice: 50, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['600990007672'] },
  { name: 'Yoo nax double cheese', category: 'Snacks', unitPrice: 100, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['600967510098'] },
  { name: 'Yoyo Chips Onion (30g)', category: 'Snacks', unitPrice: 1000, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['600953701662'] },
  { name: 'Yoyo Nax BBQ Redish (15g)', category: 'Snacks', unitPrice: 100, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['600967510095'] },
  { name: 'Yoyo nax cheese and onion', category: 'Snacks', unitPrice: 100, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['600967510099'] },
  { name: 'Yoyo Nax Fried Chicken (15g)', category: 'Snacks', unitPrice: 100, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['600967510093'] },
  { name: 'Yoyo Nax Fruit Chutney (15g)', category: 'Snacks', unitPrice: 100, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['600967510096'] },
  { name: 'Yoyo Nax Mexican Chill (15g)', category: 'Snacks', unitPrice: 100, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['600967510097'] },
  { name: 'yoyo nax smoked beef', category: 'Snacks', unitPrice: 100, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['600967510092'] },
  { name: 'Yoyo nax tomatoe flavour', category: 'Snacks', unitPrice: 100, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['600967510094'] },
  { name: 'Zumba c cheese n chives nacks', category: 'Snacks', unitPrice: 50, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['600980430704'] },
  { name: '7 UP 500mls', category: 'Soft Drinks', unitPrice: 1500, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['600980322789'] },
  { name: 'Amasipsip Banana (500ml)', category: 'Soft Drinks', unitPrice: 1200, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['600971132571'] },
  { name: 'Amasipsip Butter Cream (500ml)', category: 'Soft Drinks', unitPrice: 1200, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['600971132573'] },
  { name: 'Amasipsip Chibwantu (500ml)', category: 'Soft Drinks', unitPrice: 1000, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['600964499377'] },
  { name: 'Amasipsip Sorgo (500ml)', category: 'Soft Drinks', unitPrice: 1200, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['600971132183'] },
  { name: 'Apple max 500mls', category: 'Soft Drinks', unitPrice: 1200, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['600965278559'] },
  { name: 'Bonlife basil sed drink - pineapple', category: 'Soft Drinks', unitPrice: 2900, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['893504861949'] },
  { name: 'Bonlife basil seed drink kiwi', category: 'Soft Drinks', unitPrice: 2900, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['893533022891'] },
  { name: 'Bonlife basil seeds drink', category: 'Soft Drinks', unitPrice: 2900, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['893533022892'] },
  { name: 'Bonlife basil seeds rinklychee', category: 'Soft Drinks', unitPrice: 2900, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['893533022893'] },
  { name: 'Bonlife basil seeds strawberry', category: 'Soft Drinks', unitPrice: 2900, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['893533022890'] },
  { name: 'Brothers apple 500mls', category: 'Soft Drinks', unitPrice: 1000, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['600971132398'] },
  { name: 'Brothers Mojito', category: 'Soft Drinks', unitPrice: 1000, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['600971310405'] },
  { name: 'Canned fanta orange 300mls', category: 'Soft Drinks', unitPrice: 2300, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['544900025700'] },
  { name: 'Coca Cola 300ml', category: 'Soft Drinks', unitPrice: 1000, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['90338052'] },
  { name: 'Cocacola (350ml)', category: 'Soft Drinks', unitPrice: 1000, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['42117131'] },
  { name: 'Cocacola (500ml)', category: 'Soft Drinks', unitPrice: 1500, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['54491472'] },
  { name: 'Coco Mixed Fruit (120mls)', category: 'Soft Drinks', unitPrice: 250, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['620300163042'] },
  { name: 'Coke 2ltrs', category: 'Soft Drinks', unitPrice: 3500, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['544900000028'] },
  { name: 'Coke Zero (500ml)', category: 'Soft Drinks', unitPrice: 1500, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['544900013183'] },
  { name: 'Fanta Orange (350ml)', category: 'Soft Drinks', unitPrice: 1000, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['90377884'] },
  { name: 'Fanta Orange (500ml)', category: 'Soft Drinks', unitPrice: 1500, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['40822938'] },
  { name: 'Fanta orange 2ltrs', category: 'Soft Drinks', unitPrice: 3500, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['544900001004'] },
  { name: 'Fanta passion flavour', category: 'Soft Drinks', unitPrice: 1200, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['54494022'] },
  { name: 'FIT Grape flavour 500mls', category: 'Soft Drinks', unitPrice: 1000, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['600971310726'] },
  { name: 'FIT Mixed berry 500 mls', category: 'Soft Drinks', unitPrice: 1000, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['600971310079'] },
  { name: 'Fresh Up Guabana (400ml)', category: 'Soft Drinks', unitPrice: 1200, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['600971132794'] },
  { name: 'Fresh up mixed fruits 400mls', category: 'Soft Drinks', unitPrice: 1200, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['600971132796'] },
  { name: 'Friticana orange flavour', category: 'Soft Drinks', unitPrice: 1200, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['600970982352'] },
  { name: 'Frooty original 350 mls', category: 'Soft Drinks', unitPrice: 800, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['600965278296'] },
  { name: 'Fruiticana green smoothie', category: 'Soft Drinks', unitPrice: 1500, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['600971132680'] },
  { name: 'Fruiticana yello smoothie 500mls', category: 'Soft Drinks', unitPrice: 1500, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['600971132679'] },
  { name: 'Fruititcan tamarind (kawawashsa)', category: 'Soft Drinks', unitPrice: 1200, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['600971132201'] },
  { name: 'Fruticana Guava (430ml)', category: 'Soft Drinks', unitPrice: 1200, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['600970982551'] },
  { name: 'Fruticana Mango (430ml)', category: 'Soft Drinks', unitPrice: 1200, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['600970982355'] },
  { name: 'Fruticana Mixed Berry', category: 'Soft Drinks', unitPrice: 1200, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['600971132631'] },
  { name: 'Fruticana Mixed fruit 430ml', category: 'Soft Drinks', unitPrice: 1200, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['600970982354'] },
  { name: 'Fruticana Pineapple', category: 'Soft Drinks', unitPrice: 1200, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['600970982661'] },
  { name: 'Groovy sip tant orange', category: 'Soft Drinks', unitPrice: 100, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['710497449922'] },
  { name: 'Groovy siptutti fruity', category: 'Soft Drinks', unitPrice: 100, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['710497449915'] },
  { name: 'HAVANA COLA 330MLS', category: 'Soft Drinks', unitPrice: 800, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['606110288088'] },
  { name: 'Hubbl;y bubbly 350mls', category: 'Soft Drinks', unitPrice: 600, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['600965278295'] },
  { name: 'Iced freez it', category: 'Soft Drinks', unitPrice: 300, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['Freezit'] },
  { name: 'Kung-Fu Energy (500ml)', category: 'Soft Drinks', unitPrice: 1500, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['600953701595'] },
  { name: 'KUNGFU ENERGY 300MLS', category: 'Soft Drinks', unitPrice: 1200, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['600971510178'] },
  { name: 'Kwench (500ml)', category: 'Soft Drinks', unitPrice: 100, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['kwench500'] },
  { name: 'Minute Maid Mango', category: 'Soft Drinks', unitPrice: 1500, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['544900017607'] },
  { name: 'Minute maid tropical 500g', category: 'Soft Drinks', unitPrice: 1500, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['544900003377'] },
  { name: 'Mirinda fruity flkavour 330mls', category: 'Soft Drinks', unitPrice: 1000, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['600968126715'] },
  { name: 'Mirinda red apple 500mls', category: 'Soft Drinks', unitPrice: 1300, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['600988870161'] },
  { name: 'Mojo Bitter Lemon', category: 'Soft Drinks', unitPrice: 600, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['600971510131'] },
  { name: 'Mojo Enegry Drink (330ml)', category: 'Soft Drinks', unitPrice: 600, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['600970982663'] },
  { name: 'Mojo Lime (330ml)', category: 'Soft Drinks', unitPrice: 600, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['600970982477'] },
  { name: 'Mojo Spin (330ml)', category: 'Soft Drinks', unitPrice: 600, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['600971132876'] },
  { name: 'mojo Spinn creme soda', category: 'Soft Drinks', unitPrice: 600, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['600971132875'] },
  { name: 'Mountain dew 500mls', category: 'Soft Drinks', unitPrice: 1300, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['600988071592'] },
  { name: 'Mrinda Grape (500ml)', category: 'Soft Drinks', unitPrice: 1300, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['600980322787'] },
  { name: 'Mrinda Orange (500ml)', category: 'Soft Drinks', unitPrice: 1300, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['600980322786'] },
  { name: 'One Chibwantu', category: 'Soft Drinks', unitPrice: 1200, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['072652940004'] },
  { name: 'PEPSI 330MLS', category: 'Soft Drinks', unitPrice: 1000, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['600968126764'] },
  { name: 'Pepsi Max LITE 500mls', category: 'Soft Drinks', unitPrice: 1500, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['600988870102'] },
  { name: 'pepsi pepsi 500mls', category: 'Soft Drinks', unitPrice: 1300, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['600980322784'] },
  { name: 'Shake n Sip Banana (500ml)', category: 'Soft Drinks', unitPrice: 1400, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['600964499913'] },
  { name: 'Shake n Sip Banana n', category: 'Soft Drinks', unitPrice: 1000, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['600953701575'] },
  { name: 'Shake n Sip Banana n', category: 'Soft Drinks', unitPrice: 1400, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['600953701576'] },
  { name: 'sobo cherry plum 300mls', category: 'Soft Drinks', unitPrice: 800, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['950110000823'] },
  { name: 'Sobo cocpine ready to drink', category: 'Soft Drinks', unitPrice: 800, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['950110000822'] },
  { name: 'Sprite (350ml)', category: 'Soft Drinks', unitPrice: 1000, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['40822099'] },
  { name: 'Sprite (500ml)', category: 'Soft Drinks', unitPrice: 1500, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['54491069'] },
  { name: 'Sun Dance Pineapple soft drink', category: 'Soft Drinks', unitPrice: 600, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['600970982482'] },
  { name: 'Sundance orange', category: 'Soft Drinks', unitPrice: 600, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['600970982481'] },
  { name: 'Switch energy drink 500mls', category: 'Soft Drinks', unitPrice: 2300, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['600980398243'] },
  { name: 'Tango Pina (350ml)', category: 'Soft Drinks', unitPrice: 600, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['606110288095'] },
  { name: 'Tango Pina (350ml)', category: 'Soft Drinks', unitPrice: 800, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['060611028809'] },
  { name: 'Travellers Cibwantu 750ml', category: 'Soft Drinks', unitPrice: 1200, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['079943955568'] },
  { name: 'Vatra (500ml)', category: 'Soft Drinks', unitPrice: 700, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['600970982434'] },
  { name: 'Vatra (750ml)', category: 'Soft Drinks', unitPrice: 1000, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['600970982521'] },
  { name: 'Wild Cat Energy (500ml)', category: 'Soft Drinks', unitPrice: 1300, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['600964499119'] },
  { name: 'Yes Fuit Punch (500ml)', category: 'Soft Drinks', unitPrice: 1000, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['600964492100'] },
  { name: 'Yes Pineapple (500ml)', category: 'Soft Drinks', unitPrice: 1000, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['600964492102'] },
  { name: 'Yess Fruta Embe 430ml', category: 'Soft Drinks', unitPrice: 1200, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['606110288514'] },
  { name: 'Assorted Vegtables', category: 'Vegetables', unitPrice: 500, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['assortedges1'] },
  { name: 'Cabbage Big', category: 'Vegetables', unitPrice: 1500, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['cabbageb'] },
  { name: 'Cabbage Small', category: 'Vegetables', unitPrice: 1000, unitOfMeasure: 'kg', isWeightBased: true, barcodes: ['cabbages'] },
  { name: 'Carrots medium K25', category: 'Vegetables', unitPrice: 2500, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['Carrots'] },
  { name: 'Carrots small pkt K15', category: 'Vegetables', unitPrice: 1500, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['Carrots small'] },
  { name: 'Delele K10', category: 'Vegetables', unitPrice: 1000, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['Okra'] },
  { name: 'Green Pepper medium size', category: 'Vegetables', unitPrice: 300, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['Green pepper'] },
  { name: 'Green Pepper Small size', category: 'Vegetables', unitPrice: 200, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['Green Pepper'] },
  { name: 'Gren Pepper Large size', category: 'Vegetables', unitPrice: 500, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['Greem Pepper'] },
  { name: 'Onion Big', category: 'Vegetables', unitPrice: 500, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['onoinb'] },
  { name: 'Onion Medium', category: 'Vegetables', unitPrice: 300, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['onionm'] },
  { name: 'Onion Small', category: 'Vegetables', unitPrice: 100, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['onions'] },
  { name: 'Onion Very Small', category: 'Vegetables', unitPrice: 100, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['onionvs'] },
  { name: 'small size', category: 'Vegetables', unitPrice: 50, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['Tomatoes'] },
  { name: 'Tomato (K1)', category: 'Vegetables', unitPrice: 100, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['tomato1'] },
  { name: 'Tomato (K2)', category: 'Vegetables', unitPrice: 200, unitOfMeasure: 'each', isWeightBased: false, barcodes: ['tomato2'] },
];

/** The categories this catalogue introduces, in the order a shelf walk meets them. */
export const HQ_CATEGORIES: string[] = [
  'Bakery',
  'Beef',
  'Cooking Oil',
  'Fish',
  'Flowbreeds',
  'Fruits',
  'Game Meat',
  'Goat / Mutton',
  'Groceries',
  'Juices',
  'Polony Products',
  'Pork',
  'Poultry',
  'Sausage',
  'Snacks',
  'Soft Drinks',
  'Vegetables',
];
